name = "trustedfare-enquiry"
main = "src/worker.js"
compatibility_date = "2026-09-24"

[[rules]]
type = "Text"
globs = ["**/*.html"]

[[kv_namespaces]]
binding = "ENQUIRIES"
id = "5aa25d7016784985ad8178eda34ba4d1"
